inherit:
    - models/tiny.yaml
    - wandb.yaml

model:
    n_dims: 12
    n_positions: 101

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 200001
    with_replacement: True
    curriculum:
        dims:
            start: 12
            end: 12
            inc: 0
            interval: 2000
        points:
            start: 41
            end: 41
            inc: 0
            interval: 2000
    task: linear_classification

out_dir: ../models/batch_replace

wandb:
    name: "batch_replace_classification"