inherit:
    - models/tiny.yaml
    - wandb.yaml

model:
    n_dims: 12
    n_positions: 101

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 1
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 2000001
    num_training_examples: 10000
    with_replacement: False
    curriculum:
        dims:
            start: 12
            end: 12
            inc: 0
            interval: 2000
        points:
            start: 41
            end: 41
            inc: 0
            interval: 2000
    task: linear_classification

out_dir: ../models/online_sequential

wandb:
    name: "online_sequential_classification"